title: "Jairaj Narendran"
author: "Jairaj Narendran"
description: "Work in progress"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# video for basics: https://www.youtube.com/watch?v=qZsgPgGdOzQ
# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: "Resume", file: "\Jairaj_Resume.pdf", }
  - {title: "Google Scholar", url: "https://scholar.google.com/citations?user=9v9WDlAAAAAJ&hl=en&authuser=1"}
  - {title: "Blog", file: "blog.md"}
  #- {file: "archive.html", title: "Home", sidebaricon: home}
  #- {file: "README.md", title: "About Me", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:jairajnarendran@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/jnarendran"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
