# site settings
title: Jairaj Narendran
subtitle: "@jnarendran"
email: jairajnarendran@gmail.com
description: I am a mechanical engineer commited to sustainability and improving human health outcomes.
baseurl: "" #"/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Jairaj Narendran
street_address: "(Private)"
city: Boston
state: MA
zip_code: "(Private)"
country: United States of America
phone: (817) 941-3308

# collections
collections:
  projects:
    output: true

# https://stackoverflow.com/questions/18675610/jekyll-change-layout-if-page-is-a-post
# default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: post
      is_post: true # automatically set is_post=true for all posts
      description: ""
      image: ""
      imagealt: ""
  -
    scope:
      path: ""
      type: projects
    values:
      layout: post

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jnarendran
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/jairajnarendran
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- ref_elements.md
- ref_landing.md
- ref_generic.md
